server:
  port: 8888

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/app"
    username: root
    password: lcy5201314

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
